// src/layouts/Layout/Layout.jsx
import cn from 'classnames'

const Layout = ({ className, children, ...props }) => {
  return (
    <div
      {...props}
      className={cn(
        className,
        'p-4 md:p-10 min-h-screen',
        'bg-gradient-to-br from-blue-50 to-white'
      )}
    >
      <div className='mx-auto max-w-screen-xl w-full h-full'>{children}</div>
    </div>
  )
}

export default Layout

// src/routes/__layout.svelte
<script lang="ts">
  import cn from 'classnames'
  import '../app.css'

  export let className: string
</script>

<div
  class={cn(
    className,
    'p-4 md:p-10 min-h-screen',
    'bg-gradient-to-br from-blue-50 to-white'
  )}
>
  <div class="mx-auto max-w-screen-xl w-full h-full"><slot /></div>
</div>
