// src/components/TextArea/BaseTextArea.jsx
import { forwardRef } from 'react'
import cn from 'classnames'

const TextArea = forwardRef(({ className, onChange, ...props }, ref) => {
  const handleChange = (e) => {
    if (!onChange) {
      return
    }

    onChange(e.target.value)
  }

  return (
    <textarea
      {...props}
      ref={ref}
      className={cn(
        className,
        'w-full h-full p-3 shadow-sm resize-none',
        'text-xs xs:text-base',
        'rounded-md border border-gray-300',
        'outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500'
      )}
      onChange={handleChange}
    />
  )
})

export default TextArea

// src/components/TextArea/BaseTextArea.svelte
<script lang="ts">
  import cn from 'classnames'

  export let className: string
  export let value: string
  export let placeholder = ''
</script>

<textarea
  class={cn(
    className,
    'w-full h-full p-3',
    'text-base shadow-sm resize-none',
    'rounded-md border border-gray-300',
    'outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500'
  )}
  bind:value
  {placeholder}
/>
