// src/components/TextArea/Highlighter.svelte
<script lang="ts">
  import cn from 'classnames'
  import type { Token } from 'lib/diff/types'
  import shouldConcatLeft from './utils/shouldConcatLeft'
  import shouldConcatRight from './utils/shouldConcatRight'

  export let className: string
  export let tokens: Array<Token>
</script>

<div
  class={cn(
    className,
    'w-full max-w-full h-full max-h-[99%] overflow-hidden',
    'text-base'
  )}
>
  {#each tokens as { added, removed, value }, i (`${i}::${value}`)}
    <span
      class={cn('rounded-sm', {
        'bg-green-300': added,
        'bg-red-300': removed,
        'rounded-l-none': shouldConcatLeft(tokens, i),
        'rounded-r-none': shouldConcatRight(tokens, i)
      })}
    >
      {value}
      {#if value.endsWith('\n')}
        <br />
      {/if}
    </span>
  {/each}
</div>

// src/components/TextArea/Highlighter.jsx
import { forwardRef } from 'react'
import cn from 'classnames'
import shouldConcatLeft from './utils/shouldConcatLeft'
import shouldConcatRight from './utils/shouldConcatRight'

const Highlighter = forwardRef(({ className, tokens }, ref) => {
  return (
    <div
      ref={ref}
      className={cn(
        className,
        'max-w-full max-h-[99%] overflow-hidden',
        'text-xs xs:text-base'
      )}
    >
      {tokens.map(({ added, removed, value }, i) => (
        <span
          key={`${i}:${value}`}
          className={cn('rounded-sm', {
            'bg-green-300': added,
            'bg-red-300': removed,
            'rounded-l-none': shouldConcatLeft(tokens, i),
            'rounded-r-none': shouldConcatRight(tokens, i),
          })}
        >
          {value}
          {value.endsWith('\n') && <br />}
        </span>
      ))}
    </div>
  )
})

export default Highlighter
