// src/components/TextArea/TextArea.svelte
<script lang="ts">
  import cn from 'classnames'

  export let className = ''
  export let value: string
  export let placeholder = ''
</script>

<textarea
  class={cn(
    className,
    'p-3 text-base shadow-sm resize-none',
    'rounded-md border border-gray-300',
    'outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500'
  )}
  bind:value
  {placeholder}
/>

// src/components/TextArea/TextArea.jsx
import cn from 'classnames'

const TextArea = ({ className, onChange, ...props }) => {
  const handleChange = (e) => {
    if (!onChange) {
      return
    }

    onChange(e.target.value)
  }

  return (
    <textarea
      {...props}
      className={cn(
        className,
        'p-3 w-full shadow-sm',
        'rounded-md border border-gray-300',
        'outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500'
      )}
      onChange={handleChange}
    />
  )
}

export default TextArea
