// src/pages/Home/Home.jsx
import { useState } from 'react'
import Layout from 'layouts/Layout'
import TextArea from 'components/TextArea'
import Button from 'components/Button'

const HomePage = () => {
  const [text1, setText1] = useState('')
  const [text2, setText2] = useState('')

  const handleDiff = () => {
    alert('diff')
  }

  return (
    <Layout className='h-screen '>
      <div className='flex flex-col items-center gap-6'>
        <div className='w-full flex gap-5'>
          <TextArea
            className='w-1/2 max-h-[35rem]'
            value={text1}
            rows={12}
            placeholder='Введите текст'
            onChange={setText1}
          />
          <TextArea
            className='w-1/2 max-h-[35rem]'
            value={text2}
            rows={12}
            placeholder='Введите текст'
            onChange={setText2}
          />
        </div>
        <Button onClick={handleDiff}>Сравнить</Button>
      </div>
    </Layout>
  )
}

export default HomePage

// src/pages/Home/Home.svelte
<script lang="ts">
  import texts from 'modules/texts'
  import diff from 'modules/diff'
  import DiffViewer from 'components/DiffViewer'
  import Button from 'components/Button'
  import TextArea from 'components/TextArea'

  const handleCompare = () => {
    diff.buildDiff($texts.text1, $texts.text2)
  }
  const handleFiilInExample = () => {
    texts.fillInExample()
  }
</script>

{#if $diff.left.length > 0}
  <DiffViewer className="mb-5" diff={$diff} />
{/if}
<div class="flex items-center gap-3">
  <Button appearance="primary" on:click={handleCompare}>Compare</Button>
  <Button appearance="secondary" on:click={handleFiilInExample}>Example</Button>
</div>
<div class="mt-3 flex justify-center items-center gap-3">
  <TextArea
    className="w-1/2 h-96"
    bind:value={$texts.text1}
    placeholder="Type or paste a text"
  />
  <TextArea
    className="w-1/2 h-96"
    bind:value={$texts.text2}
    placeholder="Type or paste a text"
  />
</div>
